liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: "%photo_upload_bundle.uploads_directory%"
        cache_prefix: 'cache'
#    public:
##      web_path:
#      filter_name:
#        web_root: "%photo_upload_bundle.web%"
#        cache_prefix: 'media/image'

  loaders:
    default:
      filesystem:
        data_root: "%photo_upload_bundle.uploads_destination%"
    tmp_uploads:
      filesystem:
        data_root: "/tmp"

  cache: default
  data_loader: default
  default_image: 'thumbnail.png'

  filter_sets:
    upload:
      jpeg_quality: '%photo_upload_bundle.quality%'
      format: jpg
      data_loader: tmp_uploads
      filters:
        strip: ~
        downscale:
          max: [
            '%photo_upload_bundle.width%',
            '%photo_upload_bundle.height%'
          ]

    thumbnail:
      format: png
      filters:
        thumbnail: { size: [16, 16], mode: outbound }
      png_compression_level: 8
      default_image: null

    preview:
      format: jpg
      filters:
        thumbnail: { size: [100, 100], mode: outbound }
      jpeg_quality: 80
