vich_uploader:
  db_driver: orm
  storage: file_system
  mappings:
    uploads:
      uri_prefix: '%photo_upload_bundle.origin%'
      upload_destination: '%photo_upload_bundle.uploads_destination%'
      namer: 'upload_file_namer'
      directory_namer: 'upload_file_namer'
