
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  FreedomSex\PhotoUploadBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity}'

  upload_file_namer:
    class: FreedomSex\PhotoUploadBundle\Services\Naming\VichNaming\UploadFileNamer
    public: true

  Liip\ImagineBundle\Service\FilterService: '@liip_imagine.service.filter'

  FreedomSex\PhotoUploadBundle\Services\FilterNameResolver:
    arguments:
      $webRootDir: '%path.web%'
      $cachePrefix: 'media/image'
    tags:
      - { name: "liip_imagine.cache.resolver", resolver: filter_name }
